#!/usr/bin/env python3
"""
MuvaUI Build Script
Concat semua file Lua dari src/ menjadi satu MuvaUI.lua untuk distribusi.
Urutan file penting — dependency harus dideclare sebelum yang memakainya.
"""

import os
import sys
from datetime import datetime

ROOT   = os.path.dirname(os.path.abspath(__file__))
SRC    = os.path.join(ROOT, "src")
OUT    = os.path.join(ROOT, "MuvaUI.lua")
PUBLIC = os.path.join(ROOT, "public", "MuvaUI.lua")

# Urutan concat — JANGAN ubah urutan ini sembarangan.
# Setiap file dibungkus dalam local scope agar tidak polusi global.
BUILD_ORDER = [
    # Utilities (no dependencies)
    "util/Signal.lua",
    "util/Color.lua",
    "util/Tween.lua",
    "util/Icons.lua",

    # Core (depends on util)
    "core/Flag.lua",
    "core/Theme.lua",
    "core/Layout.lua",

    # Structural (depends on core)
    "core/Section.lua",
    "core/Tab.lua",
    "core/Window.lua",

    # Components — Input
    "components/input/Toggle.lua",
    "components/input/Checkbox.lua",
    "components/input/Slider.lua",
    "components/input/NumberInput.lua",
    "components/input/TextInput.lua",
    "components/input/Textarea.lua",
    "components/input/Dropdown.lua",
    "components/input/MultiDropdown.lua",
    "components/input/Keybind.lua",
    "components/input/ColorPicker.lua",

    # Components — Display
    "components/display/Button.lua",
    "components/display/Badge.lua",
    "components/display/Tag.lua",
    "components/display/ProgressBar.lua",
    "components/display/InfoDisplay.lua",
    "components/display/Paragraph.lua",
    "components/display/CodeBlock.lua",
    "components/display/Divider.lua",

    "components/display/Avatar.lua",
    "components/display/Table.lua",
    "components/display/Separator.lua",

    # Components — Layout
    "components/layout/HStack.lua",
    "components/layout/VStack.lua",
    "components/layout/Space.lua",
    "components/layout/Accordion.lua",

    # Components — Overlay
    "components/overlay/Dialog.lua",
    "components/overlay/Popup.lua",
    "components/overlay/Toast.lua",

    # Components — System
    "components/system/KeySystem.lua",
    "components/system/LoadingScreen.lua",
    "components/system/ConfigSystem.lua",
    "components/system/Webhook.lua",

    # Components — Feedback
    "components/feedback/StateRenderer.lua",

    # Entry point (depends on everything)
    "core/Library.lua",
]

def banner():
    return f"""-- ═══════════════════════════════════════════════════════════
-- MuvaUI — Roblox UI Library
-- Built: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
-- DO NOT EDIT THIS FILE DIRECTLY.
-- Edit files in src/ and run build.py to regenerate.
-- ═══════════════════════════════════════════════════════════

"""

def build():
    missing = []
    for rel in BUILD_ORDER:
        path = os.path.join(SRC, rel.replace("/", os.sep))
        if not os.path.exists(path):
            missing.append(rel)

    if missing:
        print(f"[WARN] {len(missing)} file(s) not yet created (will be skipped):")
        for m in missing:
            print(f"  - {m}")
        print()

    parts = [banner()]
    included = 0

    for rel in BUILD_ORDER:
        path = os.path.join(SRC, rel.replace("/", os.sep))
        if not os.path.exists(path):
            continue
        with open(path, "r", encoding="utf-8") as f:
            content = f.read().strip()
        parts.append(f"-- ─── {rel} {'─' * max(0, 55 - len(rel))}\n{content}\n")
        included += 1

    # Wrap everything in a factory function that returns the Library
    wrapped = (
        "local function MuvaUIFactory()\n\n"
        + "\n\n".join(parts[1:])  # skip banner from wrap
        + "\n\nreturn Library\nend\n\n"
        + "local _ok, _result = pcall(MuvaUIFactory)\n"
        + "if not _ok then\n"
        + "    warn('[MuvaUI] Fatal error during init: ' .. tostring(_result))\n"
        + "    return nil\n"
        + "end\n"
        + "return _result\n"
    )

    output = parts[0] + wrapped  # banner + wrapped body

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(output)

    import shutil
    shutil.copy2(OUT, PUBLIC)

    size_kb = os.path.getsize(OUT) / 1024
    print(f"[OK] Built MuvaUI.lua — {included}/{len(BUILD_ORDER)} files, {size_kb:.1f} KB")
    print(f"     >> {OUT}")
    print(f"     >> {PUBLIC}")

if __name__ == "__main__":
    build()
